export const LOG_STATUS = {
  SIGNUP_ERROR_USER_FIND: "SIGNUP_ERROR_USER_FIND",
  SIGNUP_ERROR_USER_NULL: "SIGNUP_ERROR_USER_NULL",
  SIGNUP_ERROR_PASSWORD_NULL: "SIGNUP_ERROR_PASSWORD_NULL",
  SIGNUP_ERROR_UNCAUGHT_EXCEPTION: "SIGNUP_ERROR_UNCAUGHT_EXCEPTION",
  SIGNUP_ERROR_POSTGRES_ERROR: "SIGNUP_ERROR_POSTGRES_ERROR",
  SIGNUP_ERROR_DRIZZLE_ERROR: "SIGNUP_ERROR_DRIZZLE_ERROR",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
}

export const RESP_STATUS = {
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const

export const RESP_MESSAGE = {
  INTERNAL_SERVER_ERROR: "An internal error occurred while processing this request",
}
